[Desktop Entry]
Type=X-GNOME-Metatheme
Name=Clearlooks-Phénix-Plume
Name[fr]=Clearlooks-Phénix-Plume
Comment=GTK3 port of Clearlooks with Plume colors from Tango Desktop Project
Comment[fr]=Version GTK3 de Clearlooks with Plume colors from Tango Desktop Project
Encoding=UTF-8

[X-GNOME-Metatheme]
GtkTheme=Clearlooks-Phenix-Plume
MetacityTheme=Clearlooks-Phenix-Plume
IconTheme=gnome
CursorTheme=DMZ-White
CursorSize=16
ButtonLayout=:minimize,maximize,close
